language: generic
sudo: false
env:
  - HABITICA_UUID =true
  - HABITICA_TOKEN =true


branches:
  only:
    - master
    # 这里可以添加你要监控哪些branch

before_install:
 - git clone https://github.com/naapavalley/habash

script:
- ./habash/habash up "D632468C-1DCA-4178-B44F-BC1DACBC4500"
